#!/bin/bash
set -e
function info { echo -e "\e[32m[info] $*\e[39m"; }
function warn  { echo -e "\e[33m[warn] $*\e[39m"; }
function error { echo -e "\e[31m[error] $*\e[39m"; exit 1; }

# 检查是安装还是升级
if [ "$1" = "configure" ]; then

	if [ -f "/lib/armbian/factory-reset.sh" ]; then
		chmod +x /lib/armbian/factory-reset.sh > /dev/null 2>&1
	fi

	if [ -f "/lib/thirdreality/hubv3-usb-sync-latest.sh" ]; then
		chmod +x /lib/thirdreality/hubv3-usb-sync-latest.sh > /dev/null 2>&1
	fi

	if [ -f "/usr/local/bin/supervisor" ]; then
		chmod +x /usr/local/bin/supervisor > /dev/null 2>&1
	fi

	if [ -f "/etc/systemd/system/supervisor.service" ]; then
		/usr/bin/systemctl enable supervisor.service
        /usr/bin/systemctl start supervisor.service
	fi

	if [ -f "/etc/systemd/system/btgatt-config.service" ]; then
		/usr/bin/systemctl disable btgatt-config.service
	fi

	/usr/bin/systemctl daemon-reload > /dev/null 2>&1

	info "Install success."
elif [ "$1" = "fix-dependency" ]; then
    echo "fix-dependency"
fi

exit 0

