#!/bin/bash
set -e

setup_mosquitto_user() {
    echo "setup mosquitto user ..."
    if ! getent group mosquitto >/dev/null; then
        addgroup --quiet --system mosquitto
    fi

    if ! getent passwd mosquitto >/dev/null; then
        adduser --quiet --system --no-create-home --ingroup mosquitto --home /var/lib/mosquitto --shell /usr/sbin/nologin mosquitto
    fi
}

fix_permissions() {
    echo "fix permissions ..."
    chown mosquitto /var/lib/mosquitto
    test ! -e /var/log/mosquitto || chown mosquitto /var/log/mosquitto
    test ! -e /var/log/mosquitto/mosquitto.log || chown mosquitto /var/log/mosquitto/mosquitto.log
}

fix_manual_install() {
    # 检查是安装还是升级
    if [ "$1" = "configure" ]; then
        echo "Install library files ..."
        if [ -f "/usr/lib/aarch64-linux-gnu/libcjson.so.1.7.15" ]; then
            ln -snf /usr/lib/aarch64-linux-gnu/libcjson.so.1.7.15 /usr/lib/aarch64-linux-gnu/libcjson.so.1
        fi

        if [ -f "/usr/lib/aarch64-linux-gnu/libdlt.so.2.18.8" ]; then
            ln -snf /usr/lib/aarch64-linux-gnu/libdlt.so.2.18.8 /usr/lib/aarch64-linux-gnu/libdlt.so.2
        fi

        if [ -f "/usr/lib/aarch64-linux-gnu/libmosquitto.so.2.0.11" ]; then
            ln -snf /usr/lib/aarch64-linux-gnu/libmosquitto.so.2.0.11 /usr/lib/aarch64-linux-gnu/libmosquitto.so.1
        fi

        if [ -f "/usr/lib/node_modules/corepack/dist/corepack.js" ]; then
            ln -snf /usr/lib/node_modules/corepack/dist/corepack.js /usr/bin/corepack
        fi

        if [ -f "/usr/lib/node_modules/npm/bin/npm-cli.js" ]; then
            ln -snf /usr/lib/node_modules/npm/bin/npm-cli.js /usr/bin/npm
        fi

        if [ -f "/usr/lib/node_modules/npm/bin/npx-cli.js" ]; then
            ln -snf /usr/lib/node_modules/npm/bin/npx-cli.js /usr/bin/npx
        fi

        echo "Install mosquitto passwd ..."
        if [ -f "/usr/bin/mosquitto_passwd" ]; then 
            rm -rf /etc/mosquitto/passwd || true
            mosquitto_passwd -b -c /etc/mosquitto/passwd thirdreality thirdreality
        fi

        echo "Install mosquitto config ..."
        if [ -f "/etc/mosquitto/mosquitto.conf.default" ]; then 
            cp /etc/mosquitto/mosquitto.conf.default /etc/mosquitto/mosquitto.conf
        fi

        if [ -f "/opt/zigbee2mqtt/data/configuration.yaml.default" ]; then     
            cp /opt/zigbee2mqtt/data/configuration.yaml.default /opt/zigbee2mqtt/data/configuration.yaml
        fi

        echo "Install mosquitto.service and zigbee2mqtt.service ..."
        systemctl disable mosquitto.service || true
        systemctl disable zigbee2mqtt.service || true

        echo "Success"
    fi
}

case "$1" in
    configure)
        setup_mosquitto_user
        fix_permissions
        fix_manual_install
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Reload AppArmor profile
APP_PROFILE="/etc/apparmor.d/usr.sbin.mosquitto"
if [ -f "$APP_PROFILE" ] && aa-status --enabled 2>/dev/null; then
    apparmor_parser -r "$APP_PROFILE" || true
fi

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/mosquitto" ]; then
        echo "config mosquitto.service[1] ..."
        update-rc.d mosquitto defaults >/dev/null
        if [ -n "$2" ]; then
            _dh_action=restart
        else
            _dh_action=start
        fi
        invoke-rc.d --skip-systemd-native mosquitto $_dh_action || exit 1
    fi
fi
# End automatically added section

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    echo "config mosquitto.service[2] ..."
    # The following line should be removed in trixie or trixie+1
    deb-systemd-helper unmask 'mosquitto.service' >/dev/null || true

    # was-enabled defaults to true, so new installations run enable.
    if deb-systemd-helper --quiet was-enabled 'mosquitto.service'; then
        # Enables the unit on first installation, creates new
        # symlinks on upgrades if the unit file has changed.
        deb-systemd-helper enable 'mosquitto.service' >/dev/null || true
    else
        # Update the statefile to add new symlinks (if any), which need to be
        # cleaned up on purge. Also remove old symlinks.
        deb-systemd-helper update-state 'mosquitto.service' >/dev/null || true
    fi
fi
# End automatically added section

# Automatically added by dh_installsystemd/13.11.4
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if [ -d /run/systemd/system ]; then
        echo "config mosquitto.service[3] ..."
        systemctl --system daemon-reload >/dev/null || true
        if [ -n "$2" ]; then
             _dh_action=restart
        else
            _dh_action=start
        fi
        deb-systemd-invoke $_dh_action 'mosquitto.service' >/dev/null || true
    fi
fi
# End automatically added section

exit 0

