#!/bin/sh
set -e

case "$1" in
    purge)
        rm -rf /opt/zigbee2mqtt/data/database.db
        rm -rf /opt/zigbee2mqtt/data/log
        rm -rf /opt/zigbee2mqtt/data/state.json
        rm -rf /opt/zigbee2mqtt/
    ;;
    remove|abort-install|abort-upgrade|disappear)
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

