#!/bin/bash
set -e

fix_manual_install() {
    echo "fix manual install ..."
    # 检查是安装还是升级
    echo "Install library files ..."
    
    if [[ "$(/usr/bin/systemctl is-active mosquitto.service)" == "active" ]]; then
        systemctl stop mosquitto.service >/dev/null || true
    fi

    if [[ "$(/usr/bin/systemctl is-active zigbee2mqtt.service)" == "active" ]]; then
        systemctl stop zigbee2mqtt.service >/dev/null || true
    fi

    if [ -f "/lib/thirdreality/post-install-zigbee2mqtt.sh" ]; then
        chmod +x /lib/thirdreality/post-install-zigbee2mqtt.sh
    fi
}

case "$1" in
    configure)
        fix_manual_install
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

