#!/bin/bash

set -e

# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/mosquitto" ] ; then
        chmod +x "/etc/init.d/mosquitto" >/dev/null || true
fi
# End automatically added section


if [[ "$(/usr/bin/systemctl is-active mosquitto.service)" == "active" ]]; then
    echo "Stopping mosquitto.service"
    /usr/bin/systemctl stop mosquitto.service
fi

if [[ "$(/usr/bin/systemctl is-active zigbee2mqtt.service)" == "active" ]]; then
    echo "Stopping zigbee2mqtt.service"
    /usr/bin/systemctl stop zigbee2mqtt.service
fi
