#!/bin/bash

set -e


if [[ "$(/usr/bin/systemctl is-active mosquitto.service)" == "active" ]]; then
    echo "Stopping mosquitto.service"
    /usr/bin/systemctl stop mosquitto.service
fi

if [[ "$(/usr/bin/systemctl is-active zigbee2mqtt.service)" == "active" ]]; then
    echo "Stopping zigbee2mqtt.service"
    /usr/bin/systemctl stop zigbee2mqtt.service
fi
