#!/bin/bash
set -e

# 停止服务
if [ "$1" = "remove" ]; then
    echo "Remove services ..."
    systemctl stop zigbee2mqtt.service || true
    systemctl disable zigbee2mqtt.service || true

    systemctl stop mosquitto.service || true
    systemctl disable mosquitto.service || true
    
    systemctl daemon-reload

    echo "Remove library files ..."
    rm -rf /opt/zigbee2mqtt/data/log

    if [ -f "/usr/bin/pnpm" ]; then
        rm -rf /usr/bin/pnpm
    fi

    echo "Remove success."
fi

exit 0
