#!/bin/bash
set -e

# 停止服务
if [ "$1" = "remove" ]; then
    echo "Remove library files ..."
    rm -rf /usr/lib/aarch64-linux-gnu/libcjson.so.1 || true
    rm -rf /usr/lib/aarch64-linux-gnu/libdlt.so.2 || true
    rm -rf /usr/lib//usr/lib/aarch64-linux-gnu/libmosquitto.so.1 || true

    rm -rf /opt/zigbee2mqtt/data/log

    echo "Remove services ..."
    systemctl stop zigbee2mqtt.service || true
    
    systemctl disable mosquitto.service || true
    systemctl stop mosquitto.service || true
    
    systemctl daemon-reload

    echo "Remove success."
fi

exit 0
