#!/bin/bash
set -e

# Automatically added by dh_installsystemd/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
        deb-systemd-invoke stop 'mosquitto.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/mosquitto" ] ; then
        invoke-rc.d --skip-systemd-native mosquitto stop || exit 1
fi
# End automatically added section

# 停止服务
if [ "$1" = "remove" ]; then
    echo "Remove library files ..."
    rm -rf /usr/lib/aarch64-linux-gnu/libcjson.so.1 || true
    rm -rf /usr/lib/aarch64-linux-gnu/libdlt.so.2 || true
    rm -rf /usr/lib//usr/lib/aarch64-linux-gnu/libmosquitto.so.1 || true

    rm -rf /opt/zigbee2mqtt/data/log

    echo "Remove services ..."
    systemctl stop zigbee2mqtt.service || true
    
    systemctl disable mosquitto.service || true
    systemctl stop mosquitto.service || true
    
    systemctl daemon-reload

    echo "Remove success."
fi

exit 0
